export enum PermissionDomain {
  all = "all",
  auth = "auth",
  blog = "blog",
  lead = "lead",
  customer = "customer",
  presale = "presale",
  sale = "sale",
  product = "product",
  user = "user",
  dms = "dms",
  notification = "notification",
  payment = "payment",
  helpCenter = "helpCenter",
  faq = "faq",
  webinar = "webinar",
  form = "form",
  policy = "policy",
  comment = "comment",
  note = "note",
  calendar = "calendar",
  ticket = "ticket",
  expense = "expense",
  contract = "contract",
  dashboard = "dashboard",
  task = "task",
  project = "project",
}
