export * from './author.fragment'
export * from './author-detail.result.fragment'
export * from './author-detail.query'
export * from './author-list.item.result.fragment'
export * from './author-list.query'
export * from './author-create.mutation'
export * from './author-delete.mutation'
export * from './author-update.mutation'
