export enum NoteTargetType {
  Lead = "Lead",
  Customer = "Customer",
  Estimate = "Estimate",
  Proposal = "Proposal",
  Invoice = "Invoice",
  Task = "Task",
  Ticket = "Ticket",
  Organization = "Organization",
  User = "User",
  Expense = "Expense",
  Appointment = "Appointment",
  Project = "Project",
  Contract = "Contract",
}
