export * from "./organizationSettings-common-update-own.input";
export * from "./organizationSettings-common-update-own.result";
export * from "./organizationSettings-detail.input";
export * from "./organizationSettings-detail.result";
export * from "./organizationSettings-list.input";
export * from "./organizationSettings-list.item.result";
export * from "./organizationSettings-list.result";
export * from "./organizationSettings-update.input";
export * from "./organizationSettings-update.result";
