export * from "./organizationSettings-common-update-own.mutation";
export * from "./organizationSettings-detail-own.query";
export * from "./organizationSettings-detail.query";
export * from "./organizationSettings-detail.result.fragment";
export * from "./organizationSettings-list.item.result.fragment";
export * from "./organizationSettings-list.query";
export * from "./organizationSettings-update.mutation";
export * from "./organizationSettings-update-own.mutation";
export * from "./organizationSettings.fragment";
